-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(fe8019)",
			inactive_border = "rgb(665c54)",
		},
	},
	group = {
		col = {
			border_active = "rgb(fe8019)",
			border_inactive = "rgb(665c54)",
			border_locked_active = "rgb(cc241d)",
			border_locked_inactive = "rgb(665c54)",
		},
		groupbar = {
			col = {
				active = "rgb(fe8019)",
				inactive = "rgb(665c54)",
				locked_active = "rgb(cc241d)",
				locked_inactive = "rgb(665c54)",
			},
		},
	},
})
