-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "desc:AU Optronics 0x408D", mode = "1920x1080@60.049", position = "0x0", scale = 1, vrr = 0 })
