-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "desc:AU Optronics 0x408D", mode = "preferred", position = "2603x0", scale = 1, vrr = 0 })
hl.monitor({ output = "desc:Dell Inc. DELL P2418D MY3ND8BT028T", mode = "2560x1440@59.951", position = "0x30", scale = 1, vrr = 0 })
