[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

[colors.selection]
text = '#ebdbb2'
background = '#458588'

[colors.cursor]
text = '#1d2021'
cursor = '#fe8019'

[colors.normal]
black   = '#282828'
red     = '#ff0f02'
green   = '#40fe18'
yellow  = '#ffd202'
blue    = '#f16c00'
magenta = '#753400'
cyan    = '#FE8019'
white   = '#ffefe3'

[colors.bright]
black   = '#a5988e'
red     = '#ff5b52'
green   = '#79ff5e'
yellow  = '#ffe25e'
blue    = '#ff933b'
magenta = '#ffa65e'
cyan    = '#ffc697'
white   = '#fff8f3'
