-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")

    hl.exec_cmd("kitty", { workspace = "1" })
    hl.exec_cmd("firefox", { workspace = "3 silent" })
    hl.exec_cmd("kdeconnect-app", { workspace = "6 silent" })
    hl.exec_cmd("Telegram", { workspace = "7 silent" })
    hl.exec_cmd("spotify-launcher", { workspace = "8 silent" })
end)
-- DMS_STARTUP_END

hl.config({
	input = {
		-- empty inherits XKB_DEFAULT_LAYOUT (libxkbcommon), falls back to "us"
		kb_layout = "us, us",
        kb_variant = "dvorak",
		numlock_by_default = true,
		follow_mouse = 0,
        kb_options = "caps:swapescape,compose:ralt, grp:win_space_toggle",
        repeat_rate=40,
        repeat_delay=300,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 12,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
    animations = {
        enabled = false
    }
})

-- hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
-- hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
-- hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
-- hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
-- hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
-- hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })


    -- col.active_border = rgba(9c8565ff) rgba(92c785ff) 45deg
    -- col.inactive_border = rgba(595959aa)
hl.config({
	general = {

		col = {
			active_border = {colors = {"rgba(9c8565ff)","rgba(92c785ff)"}, angle = 45},
			inactive_border = "rgba(595959aa)",
		},
	},
	group = {
		col = {
			border_active = "rgb(fe8019)",
			border_inactive = "rgb(665c54)",
			border_locked_active = "rgb(cc241d)",
			border_locked_inactive = "rgb(665c54)",
		},
		groupbar = {
			col = {
				active = "rgb(fe8019)",
				inactive = "rgb(665c54)",
				locked_active = "rgb(cc241d)",
				locked_inactive = "rgb(665c54)",
			},
		},
	},
})

-- require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")
